# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gitsubmodule" # Specifies that Dependabot should look for updates in Git submodules.
    directory: "/" # This indicates that your .gitmodules file is in the root of your repository.
    schedule:
      interval: "weekly" # Check for updates once a week.
      day: "monday" # (Optional) You can specify the day, e.g., "monday", "tuesday", etc.
    target-branch: "main" # (Optional) The branch to create pull requests against. Defaults to the repository's default branch.
    commit-message: # (Optional) Customize the commit message for Dependabot's PRs.
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"