name: C++ Compile Test

on:
  push:
    branches: [ "main" ]
    paths: 
      - ".github/workflows/compile_test.yml"
      - "src/**"              # Watch all source files
      - "Makefile"            # Watch the Makefile
      - "src/imgui/**"        # Watch ImGui files
  pull_request:
    branches: [ "main" ]

jobs:
  compile_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libvlc-dev

    - name: Compile with Makefile
      run: make clean && make release

    - name: Check Compilation
      run: |
        if [ -f ASAPCabinetFE ]; then
          echo "Compilation successful!"
        else
          echo "Compilation failed!"
          exit 1
        fi